config/routes.rb
Rails.application.routes.draw do

  resources :meals do
    member do
      match 'przylacz', to: 'meals#join', via: [:get, :post], as: :join
    end

    resources :meal_shares do
      collection do
        delete 'zrezygnuj', to: 'meal_shares#quit', as: :quit
      end
    end

  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'konto/wyloguj', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dashboard', to: "account#dashboard", as: :dashboard
  get 'konto/edycja', to: "account#profile", as: :edit_profile
  put 'konto/', to: "account#update", as: :update_account
  get 'konto/posilki', to: "meals#mine", as: :my_meals


  get '/jak-to-dziala', to: "pages#about", as: 'about'
  get '/kontakt', to: "pages#contact", as: 'contact'


  root 'pages#landing'

end

app/views/layouts/shared/_fb_init.html.haml
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : "#{Figaro.env.facebook_app_id}",
      xfbml      : true,
      version    : 'v2.0'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/pl_PL/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

app/views/layouts/shared/_footer.html.haml
%footer.page-footer
  %div.container
    %p Dobre, smaczne i tanie jedzenie w doborowym towarzystwie

app/views/layouts/shared/_header.html.haml
.navbar.navbar-default.navbar-inverse.navbar-static-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "FoodSurfing.pl", root_path, class: "navbar-brand brand-logo"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to about_path do
            %i.fa.fa-question
            Jak to działa
        %li
          = link_to new_meal_path do
            %i.fa.fa-pie-chart
            Udostępnij posiłek
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %p.navbar-text
            == Witaj #{current_user.name}!
          %li
            = link_to dashboard_path do
              %i.fa.fa-dashboard
              Twoje konto
          %li
            = link_to destroy_user_session_path, :method => :delete do
              %i.fa.fa-sign-out
              Wyloguj się
        - else
          %li
            = link_to new_user_session_path do
              %i.fa.fa-sign-in
              Zaloguj się

app/views/layouts/shared/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "global-alert alert alert-#{name == :error ? "danger" : "info"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"