config/routes.rb
Rails.application.routes.draw do

  resources :meals do
    member do
      match 'przylacz', to: 'meals#join', via: [:get, :post], as: :join
    end

    resources :meal_shares do
      collection do
        delete 'zrezygnuj', to: 'meal_shares#quit', as: :quit
      end
    end

  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'konto/wyloguj', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dashboard', to: "account#dashboard", as: :dashboard
  get 'konto/edycja', to: "account#profile", as: :edit_profile
  put 'konto/', to: "account#update", as: :update_account
  get 'konto/posilki', to: "meals#mine", as: :my_meals


  get '/jak-to-dziala', to: "pages#about", as: 'about'
  get '/kontakt', to: "pages#contact", as: 'contact'


  root 'pages#landing'

end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :user
  has_many :meal_shares
  has_many :users, through: :meal_shares

  alias_method :participants, :users

  has_attached_file :picture, :styles => {
      :large => "1440x720>",
      :medium => "720x360",
      :small => "360x180",
      :tiny => "180x90#"
    },
    :default_url => "missing_:style.png"

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :served_at, message: "Ustal porę kiedy posiłek będzie dostępny!"
  validates_presence_of :name, message: "Podaj nazwę dania"
  validates_presence_of :description, message: "Dodaj kilka słów opisu"
  validates_presence_of :portions, message: "Wybierz liczbę porcji"
  validates_presence_of :price_per_portion, message: "Podaj cenę za porcję"

  def to_marker_json

    return {
      name: name,
      lat: user.latitude,
      lng: user.longitude
    }.to_json

  end


  def shares_left?

    portions_used = meal_shares.inject(0) { |sum, share| sum + share.ordered_portions }

    return portions_used < portions

  end


  def available_portions

    portions_used = meal_shares.inject(0) { |sum, share| sum + share.ordered_portions }

    return 1..[portions - portions_used, 3].max

  end


end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update]

  def new
    @meal = Meal.new
    @user = User.new unless user_signed_in?
  end

  def show
    @meal = Meal.find params[:id]
  end

  def create

    @meal = Meal.new(meal_params)

    if user_signed_in?
      @meal.user = current_user

      if @meal.save
        flash[:notice] = "Twój posiłek został dodany"
        redirect_to dashboard_path
      else
        flash[:error] = "Sprawdź poprawność formularza!"
        render action: "new"
      end
    else
      @user = User.new(user_params)
      @user.address_required = true

      if @user.valid? && @meal.valid?
        @meal.user = @user
        @meal.save
        @user.save
        sign_in @user

        flash[:notice] = "Twój posiłek został dodany"
        redirect_to dashboard_path
      else
        flash[:error] = "Sprawdź poprawność formularza!"
        render action: "new"
      end
    end

  end

  def edit
    @meal = current_user.meals.find(params[:id])
  end

  def update
    @meal = current_user.meals.find(params[:id])

    if @meal.update_attributes(meal_params)
      flash[:notice] = "Danie zaktualizowane"
      redirect_to dashboard_path
    else
      flash.now[:error] = "Sprawdź poprawność danych"
      render action: "edit"
    end
  end

  private

    def meal_params
      params.require(:meal).permit(:name, :description, :ingredients, :served_at, :cuttoff_time, :portions, :price_per_portion, :street_address, :city, :picture)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :bio, :street_address, :city, :latitude, :longitude)
    end

end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_fields.html.haml
%div.row
  %div.col-md-6
    %div.form-group
      = f.label :name, "Nazwa posiłku:"
      = f.text_field :name, autofocus: true, class: 'form-control' , placeholder: 'Nazwa dania'
      = f.error_message_on :name

    %div.form-group
      = f.label :description, "Opis:"
      = f.text_area :description, class: 'form-control', rows: 6, placeholder: 'Opisz  jakie jest Twoje danie'
      = f.error_message_on :description

    -#%div.form-group
      = f.label :ingredients, "Składniki:"
      = f.text_area :ingredients, class: 'form-control', placeholder: 'Opisz szczerze co wrzucasz w talerze.'
      = f.error_message_on :ingredients

  %div.col-md-6
    %div.form-group
      = f.label :served_at, "Na kiedy:"
      = f.datetime_local_field :served_at, class: 'form-control' ,placeholder: 'Gdzie dom Twoj tam żarcie Twoje'
      = f.error_message_on :served_at
      %span.help-block Kiedy posiłek będzie serwowany


    -#%div.form-group
      = f.label :cuttoff_time, "Najpóźniej do:"
      = f.datetime_local_field :cutoff_time, class: 'form-control',  placeholder: 'Rezerwuj najpóźniej do '
      %span.help-block Najpóźniejszy dopuszczalny termin rezerwacji
      = f.error_message_on :cutoff_time

    %div.row
      %div.col-md-6
        %div.form-group
          = f.label :portions, "Ile porcji przygotujesz"
          = f.select :portions, 1..10, {}, class: 'form-control' , placeholder: 'Ile porcji'
          = f.error_message_on :portions

      %div.col-md-6
        %div.form-group
          = f.label :price_per_portion, "Cena za jedną porcję"
          %div.input-group
            = f.number_field :price_per_portion, in: 1.0..20.0, step: 0.01, class: 'form-control', placeholder: 'Wpisz cenę za porcję'
            %div.input-group-addon PLN          
          = f.error_message_on :price_per_portion


    %div.form-group
      = f.label :picture, "Zdjęcie"
      = f.file_field :picture, class: 'form-control'
      = f.error_message_on :picture

app/views/meals/_list.html.haml
- if meals.size > 0
  - meals.each do |meal|
    %div.media.media-meal
      = link_to meal_path(meal), class: 'pull-left' do
        - if meal.picture
          = image_tag meal.picture.url(:tiny)
        - else
          = image_tag "Meal"

      %div.media-body
        %h4.media-heading
          = link_to meal.name, meal_path(meal)

        %div.info
          == Porcje: #{meal.portions} x #{meal.price_per_portion} PLN
        %div.date
          == Kiedy: #{I18n.l(meal.served_at, format: :short)}

app/views/meals/_mine.html.haml
%div.panel.panel-default
  %div.panel-heading
    %h3.panel-title Moje posiłki

  %div.panel-body

    - if current_user.meals.size > 0
      - current_user.meals.each do |meal|
        %div.media.media-meal
          = link_to meal_path(meal), class: 'pull-left' do
            - if meal.picture
              = image_tag meal.picture.url(:tiny)
            - else
              = image_tag "Meal"

          %div.media-body
            %h4.media-heading
              = link_to meal.name, meal_path(meal)

            %div.info
              == Porcje: #{meal.portions} x #{meal.price_per_portion} PLN
            %div.date
              == Kiedy: #{I18n.l(meal.served_at, format: :short)}

          %div.actions
            = link_to "edycja", edit_meal_path(meal)


          - if meal.meal_shares.size > 0
            %div.meal-participants
              - meal.meal_shares.each do |share|
                %div.profile-item
                  = image_tag share.user.avatar.url(:thumb), class: "rounded"
                  %span.name
                    = share.user.name
                    = "x #{share.ordered_portions}"
    - else
      %p Aktualnie, nie masz żadnych udostępnianych posiłków
  %div.panel-footer
    = link_to "Dodaj nowy posiłek", new_meal_path, class: 'btn btn-primary'

app/views/meals/edit.html.haml
%div.page-header
  %h1 Edycja


%div.page-content

  = form_for @meal, html: {multipart: true } do |f|

    %fieldset
      = render partial: 'fields', locals: {f: f}

    %fieldset.actions
      = f.submit "Dodaj posiłek", class: "btn btn-primary btn-large"

app/views/meals/index.html.haml
%div.page-header
  %h1 Posiłki

app/views/meals/join.html.haml
%div.page-header
  %h1
    = @meal.name
    %small
      &mdash;
      potwierdź zamówienie

%div.page-content

  %div.alert.alert-info
    %strong Uwaga!
    Zamierzasz zamówić porcję. Prosimy o potwierdzenie Twojego zamiaru.


  = form_

app/views/meals/new.html.haml
%div.page-header
  %h1 Dodaj posiłek


%div.page-content

  = form_for @meal do |f|


    %fieldset
      = render partial: 'fields', locals: {f: f}

    - unless current_user
      %fieldset
        %legend Twoje dane
        = fields_for @user do |fields|
          = render partial: 'devise/registrations/fields', locals: {f: fields}

    %fieldset.actions
      = f.submit "Dodaj posiłek", class: "btn btn-primary btn-large"

app/views/meals/show.html.haml
%div.page-header
  %h1= @meal.name

  %button.btn.btn-primary.js-button-share{data: {uri: meal_url(@meal)}}
    %i.fa.fa-facebook-square
    Podziel się ze znajomymi

%div.page-content
  %div.row
    %div.col-md-6
      - if @meal.picture
        %div.meal-photo.fluid-image
          = image_tag @meal.picture.url(:medium)
    %div.col-md-6
      = simple_format @meal.description

      %dl.dl-horizontal
        %dt Ilość porcji:
        %dd= @meal.portions

        %dt Cena za porcję:
        %dd== #{@meal.price_per_portion} PLN

        %dt Propozycja ważna do:
        %dd== #{I18n.l(@meal.served_at, format: :short)}

      - if @meal.participants.include?(current_user)
        %div.alert.alert-info
          %strong Jesteś na liście uczestników.
      - elsif user_signed_in? && current_user.can_order?(@meal)
        = link_to new_meal_meal_share_path(@meal), class: "btn btn-primary" do
          %i.fa.fa-pie-chart
          Chcę zamówić porcję
      - else
        - if @meal.shares_left?
          = link_to new_meal_meal_share_path(@meal), class: "btn btn-primary" do
            %i.fa.fa-pie-chart
            Chcę zamówić porcję



  - if @meal.meal_shares.size > 0
    .panel.panel-default.meal-sharing
      .panel-heading
        %h3.panel-title Już zamówili
      .panel-body
        - @meal.meal_shares.each do |share|
          %div.profile-item
            = image_tag share.user.avatar.url(:thumb), class: "rounded"
            %span.name
              = share.user.name
              = "x #{share.ordered_portions}"
            - if share.user == current_user
              = link_to quit_meal_meal_shares_path(@meal), class: 'btn btn-default', method: :delete do
                Wypisz się z listy



- content_for :sidebar do

  %div.sidebar
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Lokalizacja
      %div.panel-body
        %div#markermap
        :javascript
          MealMarker = #{@meal.to_marker_json}


    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Przygotowuje

      %div.panel-body
        %h4= @meal.user.name

        - if @meal.user.avatar
          %div.profile-avatar.small-avatar
            = image_tag @meal.user.avatar.url(:medium)
        = simple_format @meal.user.bio


- content_for :head do
  = render partial: 'layouts/shared/fb_init'

- content_for :og do
  %meta{property: "og:title", content: "#{raw @meal.name} - FoodSurfing.pl"}
  %meta{property: "og:description", content: truncate(@meal.description, length: 128)}
  %meta{property: "og:url", content: meal_url(@meal)}
  %meta{property: "og:site_name", content: "FoodSurfing.pl"}
  %meta{property: "og:type", content: "foodsurfing:meal"}
  - if @meal.picture.present?
    %meta{property: "og:image", content: image_url(@meal.picture.url(:medium))}
  - else
    %meta{property: "og:image", content: asset_url('fb.png')}